version: '3'

services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ev_assignment_laravel
    volumes:
      - ./:/var/www/html
    ports:
      - "9000:9000"

  nginx:
    image: nginx:stable-alpine
    container_name: ev_assignment_nginx
    ports:
      - "6060:80"
    volumes:
      - ./:/var/www/html
      - ./docker/volumes/nginx/default.conf:/etc/nginx/conf.d/default.conf

  db:
    image: mysql:latest
    container_name: ev_assignment_db
    restart: unless-stopped
    tty: true
    ports:
      - "4306:3306"
    volumes:
      - ./docker/volumes/db:/var/lib/mysql
    environment:
      MYSQL_USER: ev_assignment
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
